version: '3.3'
volumes:
  speedtest-logs:
    external:
      name: speedtest-logs
services:
  speedtest:
    build: .
    image: nibons/speedtest-cli:nanoserver
    container_name: speedtest-cli
    volumes:
     - speedtest-logs:c:/Logs
    restart: always
    environment:
      logfileName: 'speedtest.log'